# 1. DATABASE SECRETS (CloudNativePG)
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-secret
  namespace: "${ProjectNamespace}"
type: Opaque
stringData:
  database-s3-access-key: "${DatabaseS3AccessKey}"
  database-s3-secret-key: "${DatabaseS3SecretKey}"
---
# 2. OBSERVABILITY SECRETS (Fluent Bit)
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
type: Opaque
stringData:
  logs-s3-access-key: "${LogsS3AccessKey}"
  logs-s3-secret-key: "${LogsS3SecretKey}"
---
# 3. REGISTRY SECRETS (Storage & Auth)
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: ${ProjectNamespace}
type: Opaque
stringData:
  accessKey: "${RegistryS3AccessKey}"
  secretKey: "${RegistryS3SecretKey}"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: ${ProjectNamespace}
type: Opaque
stringData:
  htpasswd: "${RegistryHtpasswd}"
