apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  chart: hcloud-csi
  repo: https://charts.hetzner.cloud
  targetNamespace: kube-system
  version: "${CSIVersion}"
  bootstrap: true
  set:
    node.kubeletDir: "/var/lib/kubelet"
