apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  createNamespace: true
  version: "${IngressNginxVersion}"
  bootstrap: true
  set:
    controller.kind: "DaemonSet"
    controller.hostNetwork: "true"
    controller.service.type: "ClusterIP"
    controller.config.use-proxy-protocol: "true"
    controller.config.compute-full-forwarded-for: "true"
    controller.config.use-forwarded-headers: "true"
