apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  createNamespace: true
  version: "${IngressNginxVersion}"
  bootstrap: true
  valuesContent: |-
    controller:
      kind: DaemonSet
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # 1. Force rip down old pods to free host ports 80/443 immediately
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: "100%"

      # 2. Shorten wait time for Nginx to exit despite LB health check noise
      terminationGracePeriodSeconds: 10

      # 3. Wait for API and Cilium networking to be ready before starting
      extraInitContainers:
        - name: wait-for-api
          image: busybox:latest
          command: ['sh', '-c', 'until nc -zv 10.43.0.1 443; do echo waiting for apiserver; sleep 2; done;']

      # We do not need a Kubernetes LoadBalancer service because
      # the external Hetzner/DO Load Balancer routes directly to the nodes.
      service:
        type: ClusterIP

      config:
        # Mandatory: Matches the proxyprotocol = true in your Terraform LB config
        use-proxy-protocol: "true"
