apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "policy-deny-internode-access"
spec:
  description: something
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - kube-system # Let system pods do their job
  egressDeny:
    # Block traffic to the SSH port of any internal IP
    - toPorts:
        - ports:
            - port: "22"
              protocol: TCP
      toCIDR:
        - "10.0.0.0/16"
