apiVersion: v1
kind: Secret
metadata:
  name: cnpg-secret
  namespace: "${ProjectNamespace}"
type: Opaque
stringData:
  database-s3-access-key: "${DatabaseS3AccessKey}"
  database-s3-secret-key: "${DatabaseS3SecretKey}"
