apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
type: Opaque
stringData:
  logs-s3-access-key: "${LogsS3AccessKey}"
  logs-s3-secret-key: "${LogsS3SecretKey}"
