apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kube-system
spec:
  chart: kyverno
  repo: https://kyverno.github.io/kyverno/
  targetNamespace: kyverno
  createNamespace: true
  version: "${KyvernoVersion}" # e.g., 3.0.0
  bootstrap: true
  valuesContent: |-
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    cleanupController:
      replicas: 1
    reportsController:
      replicas: 1
