apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: fluent-bit
type: Opaque
stringData:
  access-key: "${LogsAccessKey}"
  secret-key: "${LogsSecretKey}"
  s3-bucket-name: "${LogsBucket}"
