k8sServiceHost: ${K8sServiceHost}
k8sServicePort: 6443
kubeProxyReplacement: true

tunnel: disabled
routingMode: native
ipv4NativeRoutingCIDR: ${VpcCidr}
devices: ${RoutingDevice}
autoDirectNodeRoutes: true
mtu: ${Mtu}
bpf:
  masquerade: true
  tproxy: true
ipam:
  mode: kubernetes
operator:
  replicas: 1
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
livenessProbe:
  enabled: true
  timeoutSeconds: 30
  failureThreshold: 20
startupProbe:
  enabled: true
  timeoutSeconds: 30
  failureThreshold: 105
resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"
