apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubearmor
  namespace: kube-system
spec:
  chart: kubearmor
  repo: https://kubearmor.github.io/charts
  targetNamespace: kubearmor
  createNamespace: true
  version: "${KubeArmorVersion}"
  bootstrap: true
  valuesContent: |-
    environment:
      name: k3s
    kubearmor:
      resources:
        limits:
          memory: 150Mi
        requests:
          cpu: 50m
          memory: 64Mi
