apiVersion: v1
kind: Secret
metadata:
  name: platform-registry-credentials
  namespace: kpack
  annotations:
    kpack.io/docker: "10.43.0.50:5000"
type: kubernetes.io/basic-auth
stringData:
  username: "admin"
  password: "${RegistryPassword}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-sa
  namespace: kpack
secrets:
  - name: platform-registry-credentials
imagePullSecrets:
  - name: platform-registry-credentials
