apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  createNamespace: true
  version: "${ArgoVersion}"
  bootstrap: true
  valuesContent: |-
    # 1. Run "Skinny" (High Availability Disabled)
    redis-ha:
      enabled: false
    controller:
      replicas: 1
    server:
      replicas: 1
      # 2. Disable internal TLS (Let Nginx handle it)
      extraArgs:
        - --insecure
      # 3. Expose via Ingress
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-${CloudEnv}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          # SSL Passthrough is NOT needed because we are running with --insecure
        hosts:
          - "${ArgoHost}"
        tls:
          - secretName: argocd-tls
            hosts:
              - "${ArgoHost}"
    # 4. Persistence (Save config if pod restarts)
    server:
      volumeMounts:
        - mountPath: /app/config
          name: argocd-cmd-params-cm-mount
    repoServer:
      replicas: 1
    applicationSet:
      replicas: 1
