apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: digitalocean-cloud-controller-manager
  namespace: kube-system
spec:
  chart: digitalocean-cloud-controller-manager
  repo: https://digitalocean.github.io/digitalocean-cloud-controller-manager
  targetNamespace: kube-system
  version: "${CCMVersion}"
  bootstrap: true
