apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  targetNamespace: kube-system
  version: "${CiliumVersion}"
  bootstrap: true
  valuesContent: |-
    k8sServiceHost: ${K8sServiceHost}
    k8sServicePort: 6443
    kubeProxyReplacement: true

    # --- HETZNER VPC ROUTING ---
    tunnel: disabled
    routingMode: native
    ipv4NativeRoutingCIDR: ${VpcCidr}      # <-- Dynamic from Terraform
    devices: ${PrivateInterface}           # <-- Dynamic (e.g., eth0 or enp7s0)
    autoDirectNodeRoutes: true
    mtu: ${NetworkMtu}                     # <-- Dynamic (1450 for Cloud, 1500 for Bare Metal)

    bpf:
      masquerade: true
      tproxy: true
    ipam:
      mode: kubernetes

    operator:
      replicas: ${OperatorReplicas}        # <-- Dynamic (1 for dev, 2 for prod)

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: false

    # ... (Probes and resources can stay hardcoded for now until you need to tune them) ...
    livenessProbe:
      enabled: true
      timeoutSeconds: 30
      failureThreshold: 20
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
