apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-secret
  namespace: project-platform # Must match where your DB Cluster lives
type: Opaque
stringData:
  ACCESS_KEY_ID: "${RegistryS3AccessKey}" # Reusing your existing vars
  SECRET_ACCESS_KEY: "${RegistryS3SecretKey}"
