apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nats
  namespace: kube-system
spec:
  chart: nats
  repo: https://nats-io.github.io/k8s/helm/charts/
  targetNamespace: nats
  version: "${NatsVersion}"
  bootstrap: true
  valuesContent: |-
    config:
      jetstream:
        enabled: true
        fileStore:
          pvc:
            enabled: true
            size: 10Gi
      cluster:
        enabled: true
        replicas: 1
        no_advertise: true
    service:
      type: ClusterIP
