apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  targetNamespace: cert-manager
  createNamespace: true
  version: "${CertManagerVersion}"
  bootstrap: true
  valuesContent: |-
    installCRDs: true
    prometheus:
      enabled: false
